export const GET_ALL_DAYS = "GET_ALL_DAYS";
export const GET_DAY_BY_ID = "GET_DAY_BY_ID";
export const SET_LOADING_TRUE = "SET_LOADING_TRUE";
export const SET_LOADING_FALSE = "SET_LOADING_FALSE";
export const FILTER_BY_MONTH = "FILTER_BY_MONTH";
export const SET_ERROR_TRUE = "SET_ERROR_TRUE";